---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden-stg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: sohag-stg
  project: default
  source:
    path: overlays/stg
    #plugin:
    #name: argocd-vault-plugin-kustomize
    repoURL: https://github.com/sohag033/kustomize.git
    targetRevision: HEAD

  syncPolicy:
       syncOptions:
       - CreateNamespace=false

       automated:
         selfHeal: true
         prune: true
