apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../vault
namespace: sohag-prod
patchesStrategicMerge:
  - svc.yaml
images:
  - name: vaultwarden
    vewName: sohag/vaultwarden
    newTag: main - 9c5b23531de4277b25a9164d7f22567488537018
