apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../vault
namespace: sohag-prod
patchesStrategicMerge:
  - svc.yaml
images:
  - name: vaultwarden
    newName: $IMAGE_NAME:main-92944064e9f618e0cbbe62a802d69c1902ca4f4b
