apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../vault
namespace: sohag-prod
patchesStrategicMerge:
  - svc.yaml
images:
  - name: vaultwarden
    newName: sohag/vaultwarden:main - 9dbd3516b17e325cdcec26ce46a8bf0057554c23
