apiVersion: v1
data:
  ADMIN_TOKEN: IG9ZNzBvK29ETHNYMVFqYWx6WVNzTUVuZ1hmRVVNTHAwMi8rY2F0WUxaandmSTl2b3hMWXp3R0FuV0M5akR0TmE=
  DATABASE_URL: cG9zdGdyZXM6Ly92YXVsdHdhcmRlbjpQZVEyTnFFWnhKUjdKQ1Jvb05uakBlYXJ0aC5yZHMuYXdzLmluZnJhLmRoLmhlYWx0aDo1NDMyL3ZhdWx0d2FyZGVu
  SMTP_PASSWORD: IEJKTnBtOHlQS0dDY01wSjhDTWdocllsZmNrV0gweWlmMHJLbEo4QXFsNTds
kind: Secret
metadata:
  creationTimestamp: "2022-05-13T20:43:32Z"
  name: vaultwarden
  namespace: sohag
type: Opaque
