---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "mongooseim"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: chat
  source:
    path: overlays/mongooseim/prod
    plugin:
      name: argocd-vault-plugin-kustomize
    repoURL: git@github.com:Coffee-Meets-Bagel/deployments.git
    targetRevision: HEAD
