---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: sohag-prod
  project: default
  source:
    path: overlays/prod
    plugin:
      name: argocd-vault-plugin-kustomize
      repoURL: https://github.com/sohag033/kustomize.git
      targetRevision: HEAD
  
  syncPolicy:
       syncOptions:
       - CreateNamespace=false
        
       automated:  
         selfHeal: true
         prune: true
